version: '3.9'

networks:
    internal:
        name: users_network
        driver: bridge

services:
    backend:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: users_backend
        container_name: users_backend
        expose:
            - 9000
        command: ["/usr/local/bin/php", "-S", "0.0.0.0:8080", "-t", "/var/www/public/"]
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - internal
        ports:
            - 80:8080
        env_file:
            - .env
    db:
        image: mysql:8
        container_name: users_db
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        networks:
            - internal
        env_file:
            - .env
